export { default as getWindowSize } from './libs/getWindowSize'
export { default as observeDomResize } from './libs/observeDomResize'
export { default as downloadFileByUrl } from './libs/downloadFileByUrl'
export { default as downloadFileByArrayBuffer } from './libs/downloadFileByArrayBuffer'
export { default as downloadFileByBolb } from './libs/downloadFileByBolb'
export { default as removeElement } from './libs/removeElement'
export { default as prevent } from './libs/prevent'
export { default as getStorage } from './libs/getStorage'
export { default as removeStorage } from './libs/removeStorage'
export { default as setStorage } from './libs/setStorage'
export { default as getRelativePos } from './libs/getRelativePos'
export { default as getJsFileBaseUrl } from './libs/getJsFileBaseUrl'
export { default as libraryFile } from './libs/libraryFile'
export { default as setCookie } from './libs/setCookie'
export { default as getCookie } from './libs/getCookie'
export { default as removeCookie } from './libs/removeCookie'
export { default as replaceClass } from './libs/replaceClass'
export { default as addClass } from './libs/addClass'
export { default as removeClass } from './libs/removeClass'
export { default as toggleClass } from './libs/toggleClass'
export { default as browser } from './libs/browser'
export { default as getRatio } from './libs/getRatio'
export { default as observeMouseWheel } from './libs/observeMouseWheel'
export { default as observeDomScroll } from './libs/observeDomScroll'
export { default as fullScreen } from './libs/fullScreen'
export { default as createXLSX } from './libs/createXLSX'
export { default as pdfToImage } from './libs/pdfToImage'
export { default as infoContainerPosition } from './libs/infoContainerPosition'
export { default as TextRainCanvas } from './libs/TextRainCanvas'
export { default as SeamlessRolling } from './libs/SeamlessRolling'
// export { default as speakText } from './libs/speakText'
export { default as copyText } from './libs/copyText'
export { default as LinearGradientColorLegend } from './libs/LinearGradientColorLegend'
export { default as WaterMark } from './libs/WaterMark'

import createStyle from './libs/createStyle'
export const style = createStyle('bt-browser-core')
export { default as WaterfallFlow } from './libs/WaterfallFlow'

